spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,gateway
  endpoint:
    gateway:
      enabled: true