spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://zipkin-server:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.web: DEBUG