apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  selector: # looks for the pods to expose
    app: eureka-server # every pod with this label will be exposed through this service
  ports:
    #    - protocol: "TCP"
    - port: 80 # listens for incoming requests from users
      nodePort: 31588
      targetPort: 8888  # looks for the port of the running container
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  selector:
    matchLabels:
      app: eureka-server
  replicas: 1 # number of replicas that will be created
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: saintrivers/eureka-server:1.0.1
          imagePullPolicy: Always
          ports:
            # the target port of the service will map to this
            - containerPort: 8888 # The port that the container is running on in the cluster