apiVersion: v1
kind: ConfigMap
metadata:
  name: task-postgres-config
  labels:
    app: task-postgres
data:
  POSTGRES_DB: task_db
  POSTGRES_USER: taskadmin
  POSTGRES_PASSWORD: taskadmsecret

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: task-postgres
spec:
  selector:
    app: task-postgres
  ports:
    - port: 5432
      nodePort: 31537
      targetPort: 5432
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-postgres
spec:
  selector:
    matchLabels:
      app: task-postgres
  template:
    metadata:
      labels:
        app: task-postgres
    spec:
      containers:
        - name: task-postgres
          image: postgres:14.4-alpine
          envFrom:
            - configMapRef:
                name: task-postgres-config
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: task-postgres-pvc