apiVersion: v1
kind: ConfigMap
metadata:
  name: user-postgres-config
  labels:
    app: user-postgres
data:
  POSTGRES_DB: user_db
  POSTGRES_USER: useradmin
  POSTGRES_PASSWORD: useradmsecret

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: user-postgres
spec:
  selector:
    app: user-postgres
  ports:
    - port: 5432
      nodePort: 31534
      targetPort: 5432
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-postgres
spec:
  selector:
    matchLabels:
      app: user-postgres
  template:
    metadata:
      labels:
        app: user-postgres
    spec:
      containers:
        - name: user-postgres
          image: postgres:14.4-alpine
          envFrom:
            - configMapRef:
                name: user-postgres-config
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: postgres-pvc