server:
  port: 8080

spring:
  application:
    name: user-service
  r2dbc:
#    url: r2dbc:pool:postgresql://192.168.49.2:31534/user_db
    url: r2dbc:pool:postgresql://user-database:5432/user_db
    username: useradmin
    password: useradmsecret
  zipkin:
    base-url: http://zipkin-server:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost
