server:
  port: 8080

spring:
  application:
    name: task-service
  r2dbc:
    #    url: r2dbc:pool:postgresql://192.168.49.2:31537/task_db
    url: r2dbc:pool:postgresql://task-database:5432/task_db
    username: taskadmin
    password: taskadmsecret
  zipkin:
    base-url: http://zipkin-server:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true
