server:
  port: 7071

spring:
  application:
    name: keycloak-client
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.saintrivers.tech/auth/realms/control-tower
          jwk-set-uri: https://auth.saintrivers.tech/auth/realms/control-tower/protocol/openid-connect/certs

keycloak:
  realm: control-tower
  resource: control-tower-microservice
  auth-server-url: https://auth.saintrivers.tech/auth
  credentials:
    secret: CQpcpyUu3fdYqAazbuEqtmrkrQqibkBC

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    hostname: localhost
    prefer-ip-address: true