spring:
  profiles:
    active: default,dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/saint-rivers/control-tower-config.git
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          clone-on-start: true
          search-paths:
            - task-service
            - user-service
            - keycloak-client
            - api-gateway
            - eureka-server
          default-label: master
          ignore-local-ssh-settings: true
  application:
    name: config-server

encrypt:
  key: ${ENCRYPTION_KEY}

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"