server:
  port: 8888

spring:
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/saint-rivers/control-tower-config.git
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          clone-on-start: true
          search-paths:
            - task-service
            - user-service
            - keycloak-client
            - api-gateway
          default-label: main
  security:
    user:
      name: root
      password: tmpsecret
  application:
    name: config-server
  zipkin:
    base-url: http://localhost:9411/
#    base-url: http://zipkin-server:9411/

encrypt:
  key: APODNU3093r2rbjzxcn09u213asdhy08WRFH

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: refresh,health